ZendDbSchema: ZendDbSchema_Db_Schema_Table Class Reference
ZendDbSchema_Db_Schema_Table Class Reference
Public Member Functions
__construct ($name=null, ZendDbSchema_Db_Adapter_SchemaCompatible $adapter=null, ZendDbSchema_Db_Schema_Loader_Table $loader=null, ZendDbSchema_Db_Schema_Generator_Table $generator=null)
__set ($name, $value)
__clone ()
getColumnClass ()
getIndexClass ()
getForeignClass ()
setFromArray (array $schema)
toArray ()
columns ()
primary (ZendDbSchema_Db_Schema_Table_PrimaryKey $primary=null)
indexes ()
foreigns ()
toSql ($alter=false)
isDirty ($param=null)
Public Member Functions inherited from ZendDbSchema_Db_Schema_AbstractEntity
reload ()
refresh ($param=null)
__wakeup ()
exec ($sql)
save ()
delete ()
getGenerator ()
getAdapter ()
Public Member Functions inherited from ZendDbSchema_Db_Schema_AbstractSchema
isExist ()
getCleanSchema ($param=null)
__construct ($name=null)
init ()
__toString ()
__get ($name)
__isset ($name)
__unset ($name)
getIterator ()
setName ($name)
getName ()
getOriginName ()
getDropSql ()
Public Attributes
const CHARSET_KEY = 'charset'
const COLUMNS_KEY = 'columns'
const INDEXES_KEY = 'indexes'
const FOREIGNS_KEY = 'foreigns'
const PRIMARY_KEY = 'primary'
Protected Member Functions
_getAlterSql ()
_getCreateSql ()
_getDropSql ()
_doReload ()
Protected Member Functions inherited from ZendDbSchema_Db_Schema_AbstractEntity
_delete ()
_postDelete ()
_save ()
_postSave ()
_getCleanSchema ()
Protected Attributes
$_columnsManagerClass = 'ZendDbSchema_Db_Schema_Table_DefinitionManager_Column'
$_indexesManagerClass = 'ZendDbSchema_Db_Schema_Table_DefinitionManager_Index'
$_foreignsManagerClass = 'ZendDbSchema_Db_Schema_Table_DefinitionManager_ForeignKey'
$_columnClass = 'ZendDbSchema_Db_Schema_Table_Column'
$_indexClass = 'ZendDbSchema_Db_Schema_Table_Index'
$_foreignClass = 'ZendDbSchema_Db_Schema_Table_ForeignKey'
$_primaryKeyClass = 'ZendDbSchema_Db_Schema_Table_PrimaryKey'
$_columns
$_indexes
$_foreigns
$_primary
$_loader
Protected Attributes inherited from ZendDbSchema_Db_Schema_AbstractEntity
$_adapter
$_generator
$_cleanSchema = array()
Protected Attributes inherited from ZendDbSchema_Db_Schema_AbstractSchema
$_params = array()
$_name
Additional Inherited Members
Static Public Member Functions inherited from ZendDbSchema_Db_Schema_AbstractEntity
static getDefaultAdapter ()
Detailed Description
Definition at line 29 of file Table.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Schema_Table::__construct ($name = null, ZendDbSchema_Db_Adapter_SchemaCompatible $adapter = null, ZendDbSchema_Db_Schema_Loader_Table $loader = null, ZendDbSchema_Db_Schema_Generator_Table $generator = null)
Constructor
Parameters:
string $name
ZendDbSchema_Db_Adapter_SchemaCompatible $adapter
ZendDbSchema_Db_Schema_Loader_Interface $loader
ZendDbSchema_Db_Schema_Generator_Interface $generator
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 115 of file Table.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Table::__clone ()
Clone schema
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 167 of file Table.php.
ZendDbSchema_Db_Schema_Table::__set ($name, $value)
Set schema params
Parameters:
string $name
array $value
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 153 of file Table.php.
ZendDbSchema_Db_Schema_Table::_doReload () protected
Refresh table schema
Returns:
boolen
Reimplemented from ZendDbSchema_Db_Schema_AbstractEntity.
Definition at line 430 of file Table.php.
ZendDbSchema_Db_Schema_Table::_getAlterSql () protected
See also:
ZendDbSchema_Db_Schema_AbstractEntity::_getAlterSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 404 of file Table.php.
ZendDbSchema_Db_Schema_Table::_getCreateSql () protected
See also:
ZendDbSchema_Db_Schema_AbstractEntity::_getCreateSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 412 of file Table.php.
ZendDbSchema_Db_Schema_Table::_getDropSql () protected
See also:
ZendDbSchema_Db_Schema_AbstractSchema::_getDropSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 420 of file Table.php.
ZendDbSchema_Db_Schema_Table::columns ()
Get columns
Returns:
ZendDbSchema_Db_Schema_Table_DefinitionManager_Column
Definition at line 271 of file Table.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Mysql_Table\createTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\createTable(), isDirty(), setFromArray(), toArray(), and toSql().
ZendDbSchema_Db_Schema_Table::foreigns ()
Get forign keys
Returns:
ZendDbSchema_Db_Schema_Table_DefinitionManager_Foreign
Definition at line 313 of file Table.php.
Referenced by isDirty(), setFromArray(), toArray(), and toSql().
ZendDbSchema_Db_Schema_Table::getColumnClass ()
Get column classname
Returns:
string
Definition at line 182 of file Table.php.
ZendDbSchema_Db_Schema_Table::getForeignClass ()
Get foreign key classname
Returns:
string
Definition at line 202 of file Table.php.
ZendDbSchema_Db_Schema_Table::getIndexClass ()
Get index classname
Returns:
string
Definition at line 192 of file Table.php.
ZendDbSchema_Db_Schema_Table::indexes ()
Get indexes
Returns:
ZendDbSchema_Db_Schema_Table_DefinitionManager_Index
Definition at line 300 of file Table.php.
Referenced by isDirty(), setFromArray(), toArray(), and toSql().
ZendDbSchema_Db_Schema_Table::isDirty ($param = null)
Is dirty schema or param
Parameters:
string | null $param
Returns:
boolean
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 365 of file Table.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterTable(), and toSql().
ZendDbSchema_Db_Schema_Table::primary (ZendDbSchema_Db_Schema_Table_PrimaryKey $primary = null)
Get or replace primary key
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $primary
Returns:
ZendDbSchema_Db_Schema_Table_PrimaryKey
Definition at line 285 of file Table.php.
Referenced by isDirty(), setFromArray(), toArray(), and toSql().
ZendDbSchema_Db_Schema_Table::setFromArray (array $schema)
Set schema from array
Parameters:
array $schema
Returns:
self
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 213 of file Table.php.
Referenced by __clone().
ZendDbSchema_Db_Schema_Table::toArray ()
To array
Returns:
array
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 254 of file Table.php.
Referenced by __clone().
ZendDbSchema_Db_Schema_Table::toSql ($alter = false)
Get sql query
Parameters:
boolen $alter
Returns:
string
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 327 of file Table.php.
The documentation for this class was generated from the following file:
Db/Schema/Table.php