ZendDbSchema: ZendDbSchema_Db_Schema_Generator_Mysql_Table Class Reference
ZendDbSchema_Db_Schema_Generator_Mysql_Table Class Reference
Public Member Functions
createTable (ZendDbSchema_Db_Schema_Table $schema)
alterTable (ZendDbSchema_Db_Schema_Table $schema)
dropTable (ZendDbSchema_Db_Schema_Table $schema)
createColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
alterColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
dropColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
createIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
alterIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
dropIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
addPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
alterPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
dropPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
addForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
alterForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
dropForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
Protected Member Functions
_columnSql (ZendDbSchema_Db_Schema_Table_Column $schema)
Detailed Description
Definition at line 29 of file Table.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Generator_Mysql_Table::_columnSql (ZendDbSchema_Db_Schema_Table_Column $schema) protected
Generate
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Definition at line 128 of file Table.php.
Referenced by alterColumn(), and createColumn().
ZendDbSchema_Db_Schema_Generator_Mysql_Table::addForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
Generate CREATE FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_ForeignKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 324 of file Table.php.
Referenced by alterForeignKey().
ZendDbSchema_Db_Schema_Generator_Mysql_Table::addPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
Generate ADD PRIMARY KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 279 of file Table.php.
Referenced by alterPrimaryKey().
ZendDbSchema_Db_Schema_Generator_Mysql_Table::alterColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 182 of file Table.php.
ZendDbSchema_Db_Schema_Generator_Mysql_Table::alterForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
Generate ALTER FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_ForeignKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 358 of file Table.php.
ZendDbSchema_Db_Schema_Generator_Mysql_Table::alterIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 253 of file Table.php.
ZendDbSchema_Db_Schema_Generator_Mysql_Table::alterPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
Generate ALTER PRIMARY KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Definition at line 295 of file Table.php.
ZendDbSchema_Db_Schema_Generator_Mysql_Table::alterTable (ZendDbSchema_Db_Schema_Table $schema)
Generate ALTER TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 74 of file Table.php.
ZendDbSchema_Db_Schema_Generator_Mysql_Table::createColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 170 of file Table.php.
ZendDbSchema_Db_Schema_Generator_Mysql_Table::createIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
Generate CREATE INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 227 of file Table.php.
Referenced by alterIndex().
ZendDbSchema_Db_Schema_Generator_Mysql_Table::createTable (ZendDbSchema_Db_Schema_Table $schema)
Generate CREATE TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 38 of file Table.php.
ZendDbSchema_Db_Schema_Generator_Mysql_Table::dropColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
Generate CREATE INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 213 of file Table.php.
ZendDbSchema_Db_Schema_Generator_Mysql_Table::dropForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
Generate DROP FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 374 of file Table.php.
Referenced by alterForeignKey().
ZendDbSchema_Db_Schema_Generator_Mysql_Table::dropIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
Generate DROP INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 264 of file Table.php.
Referenced by createIndex().
ZendDbSchema_Db_Schema_Generator_Mysql_Table::dropPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
Generate DROP PRIMARY KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 310 of file Table.php.
Referenced by alterPrimaryKey().
ZendDbSchema_Db_Schema_Generator_Mysql_Table::dropTable (ZendDbSchema_Db_Schema_Table $schema)
Generate DROP TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Table.
Definition at line 114 of file Table.php.
The documentation for this class was generated from the following file:
Db/Schema/Generator/Mysql/Table.php