ZendDbSchema: ZendDbSchema_Db_Schema_Table_Manager_AbstractManager Class Reference
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager Class Reference
Public Member Functions
add (ZendDbSchema_Db_Schema_Table_AbstractDefinition $item)
refresh ()
__construct ($config, ZendDbSchema_Db_Schema_Table $table)
isDirty ()
toArray ()
getIterator ()
has ($name)
get ($name)
Protected Member Functions
_getItemClass ()
Protected Attributes
$_data = array()
$_table
Detailed Description
Definition at line 29 of file AbstractManager.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::__construct ($ config, ZendDbSchema_Db_Schema_Table $ table)
Constructor
Parameters:
array $config
ZendDbSchema_Db_Schema_Table $parent
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 66 of file AbstractManager.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::_getItemClass () [abstract, protected]
Get classname
Returns:
string
Reimplemented in ZendDbSchema_Db_Schema_Table_Manager_Column, and ZendDbSchema_Db_Schema_Table_Manager_Index.
Referenced by __construct().
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::add (ZendDbSchema_Db_Schema_Table_AbstractDefinition $ item) [abstract]
Add item
Reimplemented in ZendDbSchema_Db_Schema_Table_Manager_Column, and ZendDbSchema_Db_Schema_Table_Manager_Index.
Referenced by __construct().
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::get ($ name)
Get item
Parameters:
string $name
Returns:
boolen
Definition at line 134 of file AbstractManager.php.
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::has ($ name)
Has item
Parameters:
string $name
Returns:
false|array index
Definition at line 123 of file AbstractManager.php.
Referenced by __construct(), ZendDbSchema_Db_Schema_Table_Manager_Column\add(), and ZendDbSchema_Db_Schema_Table_Manager_Index\add().
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::isDirty ()
Is items dirty
Returns:
boolean
Definition at line 87 of file AbstractManager.php.
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::refresh () [abstract]
Add item
Reimplemented in ZendDbSchema_Db_Schema_Table_Manager_Column, and ZendDbSchema_Db_Schema_Table_Manager_Index.
Referenced by __construct().
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::toArray ()
To array
Returns:
array
Definition at line 102 of file AbstractManager.php.
The documentation for this class was generated from the following file:
Db/Schema/Table/Manager/AbstractManager.php