ZendDbSchema: ZendDbSchema_Db_Schema_Table_PrimaryKey Class Reference
ZendDbSchema_Db_Schema_Table_PrimaryKey Class Reference
Public Member Functions
__construct (ZendDbSchema_Db_Schema_Table $table=null)
setColumns (array $columns)
hasColumn ($columnName)
addColumn ($columnName)
getColumns ()
removeColumn ($columnName)
Public Member Functions inherited from ZendDbSchema_Db_Schema_Table_AbstractDefinition
__construct ($name, ZendDbSchema_Db_Schema_Table $table=null)
__clone ()
__set ($name, $value)
isDirty ($param=null)
toSql ($alter=false)
getTable ()
markDeleted ($toDelete=true)
isDeleted ()
Public Member Functions inherited from ZendDbSchema_Db_Schema_AbstractSchema
isExist ()
getCleanSchema ($param=null)
refresh ($param=null)
__construct ($name=null)
init ()
__toString ()
__get ($name)
__isset ($name)
__unset ($name)
getIterator ()
setFromArray (array $schema)
toArray ()
setName ($name)
getName ()
getOriginName ()
getDropSql ()
Public Attributes
const COLUMNS_KEY = 'columns'
const TYPE_KEY = 'type'
Protected Member Functions
_getSchemaKey ()
_getDropSql ()
_getAlterSql ()
_getCreateSql ()
_getCleanSchema ()
Additional Inherited Members
Protected Attributes inherited from ZendDbSchema_Db_Schema_Table_AbstractDefinition
$_table
$_toDelete
Protected Attributes inherited from ZendDbSchema_Db_Schema_AbstractSchema
$_params = array()
$_name
Detailed Description
Definition at line 3 of file PrimaryKey.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Schema_Table_PrimaryKey::__construct (ZendDbSchema_Db_Schema_Table $table = null)
Constructor
Parameters:
string $name
ZendDbSchema_Db_Schema_Table $table
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 50 of file PrimaryKey.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Table_PrimaryKey::_getAlterSql () protected
See also:
ZendDbSchema_Db_Schema_Table_AbstractDefinition::_getAlterSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 30 of file PrimaryKey.php.
ZendDbSchema_Db_Schema_Table_PrimaryKey::_getCleanSchema () protected
Get clean schema
Returns:
array
Reimplemented from ZendDbSchema_Db_Schema_Table_AbstractDefinition.
Definition at line 65 of file PrimaryKey.php.
ZendDbSchema_Db_Schema_Table_PrimaryKey::_getCreateSql () protected
See also:
ZendDbSchema_Db_Schema_Table_AbstractDefinition::_getCreateSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 38 of file PrimaryKey.php.
ZendDbSchema_Db_Schema_Table_PrimaryKey::_getDropSql () protected
See also:
ZendDbSchema_Db_Schema_AbstractSchema::_getDropSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 22 of file PrimaryKey.php.
ZendDbSchema_Db_Schema_Table_PrimaryKey::_getSchemaKey () protected
Get schema key
Returns:
string
Reimplemented from ZendDbSchema_Db_Schema_Table_AbstractDefinition.
Definition at line 14 of file PrimaryKey.php.
Referenced by _getCleanSchema().
ZendDbSchema_Db_Schema_Table_PrimaryKey::addColumn ($columnName)
Add column
Parameters:
string $columnName
Returns:
boolen
Definition at line 107 of file PrimaryKey.php.
ZendDbSchema_Db_Schema_Table_PrimaryKey::getColumns ()
Get columns
Returns:
array
Definition at line 122 of file PrimaryKey.php.
Referenced by addColumn(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\addPrimaryKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\addPrimaryKey(), hasColumn(), and removeColumn().
ZendDbSchema_Db_Schema_Table_PrimaryKey::hasColumn ($columnName)
Has column
Parameters:
string $columnName
Returns:
boolen
Definition at line 96 of file PrimaryKey.php.
Referenced by addColumn(), and removeColumn().
ZendDbSchema_Db_Schema_Table_PrimaryKey::removeColumn ($columnName)
Remove column
Parameters:
string $columnName
Returns:
boolen
Definition at line 134 of file PrimaryKey.php.
ZendDbSchema_Db_Schema_Table_PrimaryKey::setColumns (array $columns)
Set columns
Parameters:
array $columns
Returns:
self
Definition at line 84 of file PrimaryKey.php.
Referenced by addColumn(), and removeColumn().
The documentation for this class was generated from the following file:
Db/Schema/Table/PrimaryKey.php