ZendDbSchema: ZendDbSchema_Db_Schema_AbstractSchema Class Reference
ZendDbSchema_Db_Schema_AbstractSchema Class Reference
Public Member Functions
isExist ()
isDirty ($param=null)
getCleanSchema ($param=null)
refresh ($param=null)
__construct ($name=null)
init ()
__toString ()
__get ($name)
__isset ($name)
__set ($name, $value)
__unset ($name)
__clone ()
getIterator ()
setFromArray (array $schema)
toArray ()
setName ($name)
getName ()
getOriginName ()
getDropSql ()
toSql ($alter=false)
Public Attributes
const NAME_KEY = 'name'
Protected Member Functions
_getCleanSchema ()
_getAlterSql ()
_getCreateSql ()
_getDropSql ()
Protected Attributes
$_params = array()
$_name
Detailed Description
Definition at line 29 of file AbstractSchema.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Schema_AbstractSchema::__construct ($name = null)
Constructor
Parameters:
string $name
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 154 of file AbstractSchema.php.
Member Function Documentation
ZendDbSchema_Db_Schema_AbstractSchema::__clone ()
Clone schema
Reimplemented in ZendDbSchema_Db_Schema_Table, and ZendDbSchema_Db_Schema_Table_AbstractDefinition.
Definition at line 241 of file AbstractSchema.php.
ZendDbSchema_Db_Schema_AbstractSchema::__get ($name)
Retrieve database param value
Parameters:
string $paramName
Returns:
string
Exceptions:
ZendDbSchema_Db_Schema_Exception if the $name is not a param in the schema.
Definition at line 193 of file AbstractSchema.php.
Referenced by ZendDbSchema_Db_Schema_Database\getCharset(), ZendDbSchema_Db_Schema_Table_Index\getColumns(), ZendDbSchema_Db_Schema_Table_PrimaryKey\getColumns(), ZendDbSchema_Db_Schema_Table_ForeignKey\getColumns(), getName(), ZendDbSchema_Db_Schema_Table_ForeignKey\getOnDelete(), ZendDbSchema_Db_Schema_Table_ForeignKey\getOnUpdate(), ZendDbSchema_Db_Schema_Table_ForeignKey\getReferences(), isDirty(), ZendDbSchema_Db_Schema_Table\isDirty(), ZendDbSchema_Db_Schema_Table_Column\isNullable(), and ZendDbSchema_Db_Schema_Table_Column\isSigned().
ZendDbSchema_Db_Schema_AbstractSchema::__isset ($name)
Test existence of row field
Parameters:
string $name
Returns:
boolean
Definition at line 207 of file AbstractSchema.php.
Referenced by __get(), __unset(), isDirty(), and ZendDbSchema_Db_Schema_Table\isDirty().
ZendDbSchema_Db_Schema_AbstractSchema::__set ($name, $value)
Set schema params
Parameters:
string $name
array $value
Reimplemented in ZendDbSchema_Db_Schema_Table, ZendDbSchema_Db_Schema_Database, and ZendDbSchema_Db_Schema_Table_AbstractDefinition.
Definition at line 218 of file AbstractSchema.php.
Referenced by __clone(), refresh(), setFromArray(), and setName().
ZendDbSchema_Db_Schema_AbstractSchema::__toString ()
Get sql representation of schema
Returns:
string
Definition at line 181 of file AbstractSchema.php.
ZendDbSchema_Db_Schema_AbstractSchema::__unset ($name)
Unset row field value
Parameters:
string $name
Returns:
self
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 230 of file AbstractSchema.php.
ZendDbSchema_Db_Schema_AbstractSchema::_getAlterSql () abstract protected
Get sql query
Returns:
string
Reimplemented in ZendDbSchema_Db_Schema_Table, ZendDbSchema_Db_Schema_Database, ZendDbSchema_Db_Schema_Table_Column, ZendDbSchema_Db_Schema_Table_ForeignKey, ZendDbSchema_Db_Schema_Table_Index, and ZendDbSchema_Db_Schema_Table_PrimaryKey.
Referenced by toSql().
ZendDbSchema_Db_Schema_AbstractSchema::_getCleanSchema () abstract protected
Get clean schema
Returns:
array
Reimplemented in ZendDbSchema_Db_Schema_AbstractEntity, ZendDbSchema_Db_Schema_Table_AbstractDefinition, and ZendDbSchema_Db_Schema_Table_PrimaryKey.
Referenced by getCleanSchema().
ZendDbSchema_Db_Schema_AbstractSchema::_getCreateSql () abstract protected
Get sql query
Returns:
string
Reimplemented in ZendDbSchema_Db_Schema_Table, ZendDbSchema_Db_Schema_Database, ZendDbSchema_Db_Schema_Table_Column, ZendDbSchema_Db_Schema_Table_ForeignKey, ZendDbSchema_Db_Schema_Table_Index, and ZendDbSchema_Db_Schema_Table_PrimaryKey.
Referenced by toSql().
ZendDbSchema_Db_Schema_AbstractSchema::_getDropSql () abstract protected
Get sql query
Returns:
string
Reimplemented in ZendDbSchema_Db_Schema_Table, ZendDbSchema_Db_Schema_Database, ZendDbSchema_Db_Schema_Table_Column, ZendDbSchema_Db_Schema_Table_ForeignKey, ZendDbSchema_Db_Schema_Table_Index, and ZendDbSchema_Db_Schema_Table_PrimaryKey.
Referenced by getDropSql().
ZendDbSchema_Db_Schema_AbstractSchema::getCleanSchema ($param = null)
Get clean schema
Parameters:
string $param
Returns:
array|null
Definition at line 120 of file AbstractSchema.php.
Referenced by isDirty(), ZendDbSchema_Db_Schema_Table\isDirty(), isExist(), and refresh().
ZendDbSchema_Db_Schema_AbstractSchema::getDropSql ()
Get sql query
Returns:
string
Definition at line 327 of file AbstractSchema.php.
Referenced by ZendDbSchema_Db_Schema_AbstractEntity\delete(), and ZendDbSchema_Db_Schema_Table_AbstractDefinition\toSql().
ZendDbSchema_Db_Schema_AbstractSchema::getIterator ()
Get iterator
Required by the IteratorAggregate implementation
Returns:
ArrayIterator
Definition at line 257 of file AbstractSchema.php.
ZendDbSchema_Db_Schema_AbstractSchema::getName ()
Get name
Returns:
string
Definition at line 304 of file AbstractSchema.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Database\alterDatabase(), ZendDbSchema_Db_Schema_Generator_Pgsql_Database\alterDatabase(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\createColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\createColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Database\createDatabase(), ZendDbSchema_Db_Schema_Generator_Pgsql_Database\createDatabase(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\createIndex(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\createIndex(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\createTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\createTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\dropColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\dropColumn(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\dropIndex(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\dropIndex(), getOriginName(), and ZendDbSchema_Db_Schema_AbstractEntity\save().
ZendDbSchema_Db_Schema_AbstractSchema::getOriginName ()
Get name
Returns:
string
Definition at line 314 of file AbstractSchema.php.
Referenced by ZendDbSchema_Db_Schema_Database\_doReload(), ZendDbSchema_Db_Schema_Table\_doReload(), ZendDbSchema_Db_Schema_Table_AbstractDefinition\_getCleanSchema(), ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager\add(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\addForeignKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\addForeignKey(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\dropForeignKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\dropForeignKey(), and ZendDbSchema_Db_Schema_AbstractEntity\reload().
ZendDbSchema_Db_Schema_AbstractSchema::init ()
Initialize object
Called from __construct() as final step of object instantiation.
Returns:
void
Definition at line 172 of file AbstractSchema.php.
Referenced by ZendDbSchema_Db_Schema_Table_PrimaryKey\__construct(), and __construct().
ZendDbSchema_Db_Schema_AbstractSchema::isDirty ($param = null)
Is dirty schema or param
Parameters:
string | null $param
Returns:
boolean
Reimplemented in ZendDbSchema_Db_Schema_Table, and ZendDbSchema_Db_Schema_Table_AbstractDefinition.
Definition at line 91 of file AbstractSchema.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Mysql_Database\alterDatabase(), ZendDbSchema_Db_Schema_Generator_Pgsql_Database\alterDatabase(), ZendDbSchema_Db_Schema_AbstractEntity\save(), and toSql().
ZendDbSchema_Db_Schema_AbstractSchema::isExist ()
Check if entity exists in database
Returns:
boolen
Definition at line 79 of file AbstractSchema.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Database\alterDatabase(), ZendDbSchema_Db_Schema_Generator_Pgsql_Database\alterDatabase(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterForeignKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterForeignKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\createIndex(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\createIndex(), ZendDbSchema_Db_Schema_AbstractEntity\delete(), ZendDbSchema_Db_Schema_Generator_Mysql_Database\dropDatabase(), ZendDbSchema_Db_Schema_Generator_Pgsql_Database\dropDatabase(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\dropTable(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\dropTable(), getDropSql(), ZendDbSchema_Db_Schema_Table_AbstractDefinition\markDeleted(), ZendDbSchema_Db_Schema_AbstractEntity\save(), ZendDbSchema_Db_Schema_Table\toSql(), and toSql().
ZendDbSchema_Db_Schema_AbstractSchema::refresh ($param = null)
Refresh database schema
Parameters:
string $param
Returns:
self
Reimplemented in ZendDbSchema_Db_Schema_AbstractEntity.
Definition at line 138 of file AbstractSchema.php.
Referenced by ZendDbSchema_Db_Schema_Table_PrimaryKey\__construct(), and __construct().
ZendDbSchema_Db_Schema_AbstractSchema::setFromArray (array $schema)
Set schema from array
Parameters:
array $schema
Returns:
self
Reimplemented in ZendDbSchema_Db_Schema_Table.
Definition at line 268 of file AbstractSchema.php.
Referenced by refresh().
ZendDbSchema_Db_Schema_AbstractSchema::setName ($name)
Set name
Parameters:
string $name
Returns:
self
Definition at line 293 of file AbstractSchema.php.
ZendDbSchema_Db_Schema_AbstractSchema::toArray ()
To array
Returns:
array
Reimplemented in ZendDbSchema_Db_Schema_Table.
Definition at line 282 of file AbstractSchema.php.
Referenced by getIterator().
ZendDbSchema_Db_Schema_AbstractSchema::toSql ($alter = false)
Get sql representation
Parameters:
boolen $alter
Returns:
string
Reimplemented in ZendDbSchema_Db_Schema_Table, and ZendDbSchema_Db_Schema_Table_AbstractDefinition.
Definition at line 341 of file AbstractSchema.php.
Referenced by __toString(), and ZendDbSchema_Db_Schema_AbstractEntity\save().
The documentation for this class was generated from the following file:
Db/Schema/AbstractSchema.php