ZendDbSchema: ZendDbSchema_Tool_Project_Provider_Schema Class Reference
ZendDbSchema_Tool_Project_Provider_Schema Class Reference
Public Member Functions
createResource (Zend_Tool_Project_Profile $profile, $schemaName, $contents, $force=false)
getContextClasses ()
pull ($type= 'table', $name= '', $force=false)
push ($type= 'table', $name= '', $force=false)
status ($type, $name)
Protected Member Functions
_findfile ($profile, $name)
_getSchema ($type, $name)
_getFilename ($type, $name)
_bootstrap ()
Detailed Description
Definition at line 29 of file Schema.php.
Member Function Documentation
ZendDbSchema_Tool_Project_Provider_Schema::_bootstrap () [protected]
Bootstrap
Exceptions:
Zend_Tool_Project_Provider_Exception
Definition at line 267 of file Schema.php.
Referenced by pull(), push(), and status().
ZendDbSchema_Tool_Project_Provider_Schema::_findfile ($ profile, $ name) [protected]
Find file
Parameters:
object $profile
string $name
Returns:
object
Definition at line 92 of file Schema.php.
Referenced by createResource(), push(), and status().
ZendDbSchema_Tool_Project_Provider_Schema::_getFilename ($ type, $ name) [protected]
Get filename
Parameters:
string $type
string $name
Returns:
string
Definition at line 257 of file Schema.php.
Referenced by pull(), push(), and status().
ZendDbSchema_Tool_Project_Provider_Schema::_getSchema ($ type, $ name) [protected]
Get schema object
Parameters:
string $type
string $name
Exceptions:
Zend_Tool_Project_Provider_Exception
Returns:
ZendDbSchema_Db_Schema_AbstractEntity
Definition at line 111 of file Schema.php.
Referenced by pull(), push(), and status().
ZendDbSchema_Tool_Project_Provider_Schema::createResource (Zend_Tool_Project_Profile $ profile, $ schemaName, $ contents, $ force = false)
This method is static for 2 reasons: 1) so that its not identifiable by the framework as something to execute 2) so that other providers can utilize this method to be able to "create" model resources. For example, you might have a larger system that wishes to create models. Instead of proxying through the Zend_Tool_Framework client and calling a command, it can setup the environment an call this method on an already known profile.
Parameters:
Zend_Tool_Project_Profile $profile
string $modelName
Returns:
Zend_Tool_Project_Profile_Resource
Definition at line 46 of file Schema.php.
Referenced by pull().
ZendDbSchema_Tool_Project_Provider_Schema::getContextClasses ()
This method returns the classes to load as contexts. Since this provider is creating 'ModelFile', it will need this context
Returns:
array
Definition at line 77 of file Schema.php.
ZendDbSchema_Tool_Project_Provider_Schema::pull ($ type = 'table', $ name = '', $ force = false)
Pull schema to config file
Parameters:
string $type table or database
string $name entity name
boolen $force overwrite existing file
Definition at line 139 of file Schema.php.
ZendDbSchema_Tool_Project_Provider_Schema::push ($ type = 'table', $ name = '', $ force = false)
Push schema from config file to database
Parameters:
string $type table or database
string $name entity name
boolen $force overwrite existing file
Definition at line 177 of file Schema.php.
ZendDbSchema_Tool_Project_Provider_Schema::status ($ type, $ name)
Show status
Parameters:
string $type
string $name
Exceptions:
Zend_Tool_Project_Provider_Exception
Definition at line 225 of file Schema.php.
The documentation for this class was generated from the following file:
Tool/Project/Provider/Schema.php