ZendDbSchema: ZendDbSchema_Db_Schema_Table_Manager_Column Class Reference
ZendDbSchema_Db_Schema_Table_Manager_Column Class Reference
Public Member Functions
add (ZendDbSchema_Db_Schema_Table_AbstractDefinition $item)
refresh ()
Protected Member Functions
_getItemClass ()
Detailed Description
Definition at line 29 of file Column.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Table_Manager_Column::_getItemClass () [protected]
See also:
ZendDbSchema_Db_Schema_Table_Manager_AbstractManager::_getItemClass()
Reimplemented from ZendDbSchema_Db_Schema_Table_Manager_AbstractManager.
Definition at line 35 of file Column.php.
Referenced by add(), and refresh().
ZendDbSchema_Db_Schema_Table_Manager_Column::add (ZendDbSchema_Db_Schema_Table_AbstractDefinition $ item)
Add column
Parameters:
ZendDbSchema_Db_Schema_Table_Column $column
Returns:
boolen
Reimplemented from ZendDbSchema_Db_Schema_Table_Manager_AbstractManager.
Definition at line 46 of file Column.php.
Referenced by refresh().
ZendDbSchema_Db_Schema_Table_Manager_Column::refresh ()
Add item
Reimplemented from ZendDbSchema_Db_Schema_Table_Manager_AbstractManager.
Definition at line 66 of file Column.php.
The documentation for this class was generated from the following file:
Db/Schema/Table/Manager/Column.php