ZendDbSchema: ZendDbSchema_Validate_Db_Schema_Chain Class Reference
ZendDbSchema_Validate_Db_Schema_Chain Class Reference
Public Member Functions
addValidator (Zend_Validate_Interface $validator, $breakChainOnFailure=false)
isValid ($value)
getMessages ()
getErrors ()
Protected Attributes
$_validators = array()
$_messages = array()
$_errors = array()
Detailed Description
Definition at line 29 of file Chain.php.
Member Function Documentation
ZendDbSchema_Validate_Db_Schema_Chain::addValidator (Zend_Validate_Interface $ validator, $ breakChainOnFailure = false)
Adds a validator to the end of the chain
If $breakChainOnFailure is true, then if the validator fails, the next validator in the chain, if one exists, will not be executed.
Parameters:
Zend_Validate_Interface $validator
boolean $breakChainOnFailure
Returns:
Zend_Validate Provides a fluent interface
Definition at line 64 of file Chain.php.
Referenced by ZendDbSchema_Validate_Db_Schema_Table_Mysql_Column\__construct(), ZendDbSchema_Validate_Db_Schema_Table_MysqlTable\__construct(), and ZendDbSchema_Validate_Db_Schema_Database_MysqlDatabase\__construct().
ZendDbSchema_Validate_Db_Schema_Chain::getErrors ()
Defined by Zend_Validate_Interface
Returns array of validation failure message codes
Returns:
array
Deprecated:
Since 1.5.0
Definition at line 123 of file Chain.php.
ZendDbSchema_Validate_Db_Schema_Chain::getMessages ()
Defined by Zend_Validate_Interface
Returns array of validation failure messages
Returns:
array
Definition at line 110 of file Chain.php.
ZendDbSchema_Validate_Db_Schema_Chain::isValid ($ value)
Returns true if and only if $value passes all validations in the chain
Validators are run in the order in which they were added to the chain (FIFO).
Parameters:
mixed $value
Returns:
boolean
Reimplemented in ZendDbSchema_Validate_Db_Schema_AbstractTable.
Definition at line 81 of file Chain.php.
The documentation for this class was generated from the following file:
Validate/Db/Schema/Chain.php