ZendDbSchema: ZendDbSchema_Db_Migration_Manager Class Reference
ZendDbSchema_Db_Migration_Manager Class Reference
Public Member Functions
__construct ($version, array $files=array(), array $options=array())
addChange ($change)
init ()
getIterator ()
getList ()
getVersion ()
getChange ($version=null)
getNext ($version=null)
hasChange ($change)
getPrevious ($version=null)
rollup ()
rolldown ()
up ($version=null)
down ($version)
compareVersion ($change, $operator=null)
isDirty ()
Protected Attributes
$_adapter
$_changes = array()
$_currentVersion
Detailed Description
Definition at line 29 of file Manager.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Migration_Manager::__construct ($ version, array $ files = array(), array $ options = array())
Constructor of Core_Migration_Manager
public
Parameters:
array $options
Definition at line 49 of file Manager.php.
Member Function Documentation
ZendDbSchema_Db_Migration_Manager::addChange ($ change)
Add change or version
Parameters:
string $change
Returns:
self
Definition at line 89 of file Manager.php.
Referenced by __construct().
ZendDbSchema_Db_Migration_Manager::compareVersion ($ change, $ operator = null)
Compare version
Parameters:
string | ZendDbSchema_Db_Migration_Change $change
string $operator
Exceptions:
ZendDbSchema_Db_Migration_Exception
Returns:
1|-1|0|true|false
Definition at line 312 of file Manager.php.
Referenced by down(), and up().
ZendDbSchema_Db_Migration_Manager::down ($ version)
Downgrade to given version
Parameters:
string $version
Exceptions:
ZendDbSchema_Db_Migration_Exception
Definition at line 290 of file Manager.php.
ZendDbSchema_Db_Migration_Manager::getChange ($ version = null)
Get current migration change instance
Parameters:
string $version
Returns:
ZendDbSchema_Db_Migration_Change
Definition at line 156 of file Manager.php.
Referenced by compareVersion(), isDirty(), rolldown(), and rollup().
ZendDbSchema_Db_Migration_Manager::getIterator ()
Get iterator
Returns:
array
Definition at line 123 of file Manager.php.
Referenced by getList(), and getNext().
ZendDbSchema_Db_Migration_Manager::getList ()
Get migrations versions list
Returns:
array
Definition at line 135 of file Manager.php.
ZendDbSchema_Db_Migration_Manager::getNext ($ version = null)
Get next migration version
Parameters:
string $version
Returns:
string
Definition at line 174 of file Manager.php.
Referenced by rollup().
ZendDbSchema_Db_Migration_Manager::getPrevious ($ version = null)
Get previous migration name
Parameters:
string $version
Returns:
string
Definition at line 202 of file Manager.php.
Referenced by rolldown().
ZendDbSchema_Db_Migration_Manager::getVersion ()
Get current migration change version
Returns:
string|null
Definition at line 145 of file Manager.php.
Referenced by compareVersion(), getChange(), getNext(), getPrevious(), and rolldown().
ZendDbSchema_Db_Migration_Manager::hasChange ($ change)
Check if migration version exists
Parameters:
string $change
Returns:
boolen
Definition at line 191 of file Manager.php.
Referenced by compareVersion(), getChange(), getNext(), and getPrevious().
ZendDbSchema_Db_Migration_Manager::init ()
Method initialize migration schema table
Definition at line 114 of file Manager.php.
Referenced by __construct().
ZendDbSchema_Db_Migration_Manager::isDirty ()
Is database dirty
Returns:
bool
Definition at line 331 of file Manager.php.
Referenced by ZendDbSchema_Tool_Project_Provider_Migration\status().
ZendDbSchema_Db_Migration_Manager::rolldown ()
Roll down
Definition at line 239 of file Manager.php.
Referenced by down().
ZendDbSchema_Db_Migration_Manager::rollup ()
Roll up
Definition at line 217 of file Manager.php.
Referenced by up().
ZendDbSchema_Db_Migration_Manager::up ($ version = null)
Update to given version
Parameters:
string $version
Exceptions:
ZendDbSchema_Db_Migration_Exception
Definition at line 270 of file Manager.php.
The documentation for this class was generated from the following file:
Db/Migration/Manager.php