ZendDbSchema: ZendDbSchema_Db_Schema_AbstractEntity Class Reference
ZendDbSchema_Db_Schema_AbstractEntity Class Reference
Public Member Functions
setValidator (Zend_Validate_Interface $validator)
reload ()
refresh ($param=null)
__construct ($name=null, ZendDbSchema_Db_Adapter_SchemaCompatible $adapter=null, ZendDbSchema_Db_Schema_Loader_Interface $loader=null, ZendDbSchema_Db_Schema_Generator_Interface $generator=null)
__wakeup ()
exec ($sql)
save ()
delete ()
isValid ()
getValidator ()
getGenerator ()
getLoader ()
getAdapter ()
Static Public Member Functions
static getDefaultAdapter ()
Protected Member Functions
_doReload ()
_delete ()
_postDelete ()
_save ()
_postSave ()
_getCleanSchema ()
Protected Attributes
$_adapter
$_loader
$_validator
$_generator
$_cleanSchema = array()
Detailed Description
Definition at line 29 of file AbstractEntity.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Schema_AbstractEntity::__construct ($ name = null, ZendDbSchema_Db_Adapter_SchemaCompatible $ adapter = null, ZendDbSchema_Db_Schema_Loader_Interface $ loader = null, ZendDbSchema_Db_Schema_Generator_Interface $ generator = null)
Constructor
Parameters:
string $name
ZendDbSchema_Db_Adapter_SchemaCompatible $adapter
ZendDbSchema_Db_Schema_Loader_Interface $loader
ZendDbSchema_Db_Schema_Generator_Interface $generator
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 161 of file AbstractEntity.php.
Member Function Documentation
ZendDbSchema_Db_Schema_AbstractEntity::__wakeup ()
Setup to do on wakeup. A de-serialized Row should not be assumed to have access to a live database connection, so set _connected = false.
Returns:
void
Definition at line 200 of file AbstractEntity.php.
ZendDbSchema_Db_Schema_AbstractEntity::_delete () [protected]
Allows pre-delete logic to be applied to database. Subclasses may override this method.
Returns:
void
Definition at line 80 of file AbstractEntity.php.
Referenced by delete().
ZendDbSchema_Db_Schema_AbstractEntity::_doReload () [abstract, protected]
Reload schema
Returns:
boolen
Reimplemented in ZendDbSchema_Db_Schema_Table, and ZendDbSchema_Db_Schema_Database.
Referenced by reload().
ZendDbSchema_Db_Schema_AbstractEntity::_getCleanSchema () [protected]
Get clean schema
Returns:
array
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 147 of file AbstractEntity.php.
ZendDbSchema_Db_Schema_AbstractEntity::_postDelete () [protected]
Allows post-insert logic to be applied to database. Subclasses may override this method.
Returns:
void
Definition at line 90 of file AbstractEntity.php.
Referenced by delete().
ZendDbSchema_Db_Schema_AbstractEntity::_postSave () [protected]
Allows post-save logic to be applied to database. Subclasses may override this method.
Returns:
void
Definition at line 110 of file AbstractEntity.php.
Referenced by save().
ZendDbSchema_Db_Schema_AbstractEntity::_save () [protected]
Allows pre-save logic to be applied to database. Subclasses may override this method.
Returns:
void
Definition at line 100 of file AbstractEntity.php.
Referenced by save().
ZendDbSchema_Db_Schema_AbstractEntity::delete ()
Delete schema from db
Returns:
self
Definition at line 251 of file AbstractEntity.php.
ZendDbSchema_Db_Schema_AbstractEntity::exec ($ sql)
Exec sql code
Parameters:
string $sql
Returns:
self
Definition at line 212 of file AbstractEntity.php.
Referenced by delete(), and save().
ZendDbSchema_Db_Schema_AbstractEntity::getAdapter ()
Get db adapter
Returns:
Zend_Db_Adapter_Abstract
Definition at line 332 of file AbstractEntity.php.
Referenced by ZendDbSchema_Db_Schema_Table\__set(), ZendDbSchema_Db_Schema_Database\__set(), ZendDbSchema_Db_Schema_Database\_doReload(), ZendDbSchema_Db_Schema_Table\_doReload(), exec(), and getValidator().
static ZendDbSchema_Db_Schema_AbstractEntity::getDefaultAdapter () [static]
Get default adapter
Exceptions:
ZendDbSchema_Db_Schema_Exception
Returns:
ZendDbSchema_Db_Adapter_SchemaCompatible
Definition at line 343 of file AbstractEntity.php.
Referenced by __construct(), and ZendDbSchema_Db_Migration_Skeleton\getAdapter().
ZendDbSchema_Db_Schema_AbstractEntity::getGenerator ()
Get sql generator
Returns:
ZendDbSchema_Db_Schema_Generator_Interface
Definition at line 312 of file AbstractEntity.php.
Referenced by ZendDbSchema_Db_Schema_Database\_getAlterSql(), ZendDbSchema_Db_Schema_Table\_getAlterSql(), ZendDbSchema_Db_Schema_Database\_getCreateSql(), ZendDbSchema_Db_Schema_Table\_getCreateSql(), ZendDbSchema_Db_Schema_Database\_getDropSql(), and ZendDbSchema_Db_Schema_Table\_getDropSql().
ZendDbSchema_Db_Schema_AbstractEntity::getLoader ()
Get schema config loader
Returns:
ZendDbSchema_Db_Schema_Loader_Interface
Definition at line 322 of file AbstractEntity.php.
Referenced by ZendDbSchema_Db_Schema_Database\_doReload(), and ZendDbSchema_Db_Schema_Table\_doReload().
ZendDbSchema_Db_Schema_AbstractEntity::getValidator ()
Get validator
Returns:
Zend_Validate_Abstract
Definition at line 284 of file AbstractEntity.php.
Referenced by isValid().
ZendDbSchema_Db_Schema_AbstractEntity::isValid ()
Validate schema
Returns:
boolen
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 271 of file AbstractEntity.php.
ZendDbSchema_Db_Schema_AbstractEntity::refresh ($ param = null)
Refresh database schema
Parameters:
string $param
Returns:
self
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 135 of file AbstractEntity.php.
Referenced by delete(), and save().
ZendDbSchema_Db_Schema_AbstractEntity::reload ()
Refresh schema
Returns:
self
Definition at line 119 of file AbstractEntity.php.
Referenced by __wakeup(), and refresh().
ZendDbSchema_Db_Schema_AbstractEntity::save ()
Save schema to db
Returns:
boolen
Definition at line 228 of file AbstractEntity.php.
ZendDbSchema_Db_Schema_AbstractEntity::setValidator (Zend_Validate_Interface $ validator) [abstract]
Set schema validator
Parameters:
Zend_Validate_Abstract $validator
Returns:
self
Reimplemented in ZendDbSchema_Db_Schema_Table, and ZendDbSchema_Db_Schema_Database.
Referenced by getValidator().
The documentation for this class was generated from the following file:
Db/Schema/AbstractEntity.php