ZendDbSchema: ZendDbSchema_Db_Schema_Table_AbstractDefinition Class Reference
ZendDbSchema_Db_Schema_Table_AbstractDefinition Class Reference
Public Member Functions
__construct ($name, ZendDbSchema_Db_Schema_Table $table=null)
__clone ()
__set ($name, $value)
isDirty ($param=null)
toSql ($alter=false)
getTable ()
markDeleted ($toDelete=true)
isDeleted ()
Public Member Functions inherited from ZendDbSchema_Db_Schema_AbstractSchema
isExist ()
getCleanSchema ($param=null)
refresh ($param=null)
__construct ($name=null)
init ()
__toString ()
__get ($name)
__isset ($name)
__unset ($name)
getIterator ()
setFromArray (array $schema)
toArray ()
setName ($name)
getName ()
getOriginName ()
getDropSql ()
Protected Member Functions
_getSchemaKey ()
_getCleanSchema ()
Protected Member Functions inherited from ZendDbSchema_Db_Schema_AbstractSchema
_getAlterSql ()
_getCreateSql ()
_getDropSql ()
Protected Attributes
$_table
$_toDelete
Protected Attributes inherited from ZendDbSchema_Db_Schema_AbstractSchema
$_params = array()
$_name
Additional Inherited Members
Public Attributes inherited from ZendDbSchema_Db_Schema_AbstractSchema
const NAME_KEY = 'name'
Detailed Description
Definition at line 29 of file AbstractDefinition.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Schema_Table_AbstractDefinition::__construct ($name, ZendDbSchema_Db_Schema_Table $table = null)
Constructor
Parameters:
string $name
ZendDbSchema_Db_Schema_Table $table
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 56 of file AbstractDefinition.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Table_AbstractDefinition::__clone ()
Clone schema
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 68 of file AbstractDefinition.php.
ZendDbSchema_Db_Schema_Table_AbstractDefinition::__set ($name, $value)
Set schema params
Parameters:
string $name
array $value
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 79 of file AbstractDefinition.php.
Referenced by ZendDbSchema_Db_Schema_Table_Index\setColumns(), ZendDbSchema_Db_Schema_Table_PrimaryKey\setColumns(), ZendDbSchema_Db_Schema_Table_ForeignKey\setColumns(), ZendDbSchema_Db_Schema_Table_ForeignKey\setOnDelete(), ZendDbSchema_Db_Schema_Table_ForeignKey\setOnUpdate(), and ZendDbSchema_Db_Schema_Table_ForeignKey\setReferences().
ZendDbSchema_Db_Schema_Table_AbstractDefinition::_getCleanSchema () protected
Get clean schema
Returns:
array
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Reimplemented in ZendDbSchema_Db_Schema_Table_PrimaryKey.
Definition at line 97 of file AbstractDefinition.php.
ZendDbSchema_Db_Schema_Table_AbstractDefinition::_getSchemaKey () abstract protected
Get schema key
Returns:
string
Reimplemented in ZendDbSchema_Db_Schema_Table_Column, ZendDbSchema_Db_Schema_Table_ForeignKey, ZendDbSchema_Db_Schema_Table_Index, and ZendDbSchema_Db_Schema_Table_PrimaryKey.
Referenced by __set(), and _getCleanSchema().
ZendDbSchema_Db_Schema_Table_AbstractDefinition::getTable ()
Get table
Returns:
string
Definition at line 145 of file AbstractDefinition.php.
Referenced by __set(), ZendDbSchema_Db_Schema_Table_PrimaryKey\_getAlterSql(), ZendDbSchema_Db_Schema_Table_Index\_getAlterSql(), ZendDbSchema_Db_Schema_Table_ForeignKey\_getAlterSql(), ZendDbSchema_Db_Schema_Table_Column\_getAlterSql(), ZendDbSchema_Db_Schema_Table_PrimaryKey\_getCleanSchema(), _getCleanSchema(), ZendDbSchema_Db_Schema_Table_PrimaryKey\_getCreateSql(), ZendDbSchema_Db_Schema_Table_Index\_getCreateSql(), ZendDbSchema_Db_Schema_Table_ForeignKey\_getCreateSql(), ZendDbSchema_Db_Schema_Table_Column\_getCreateSql(), ZendDbSchema_Db_Schema_Table_PrimaryKey\_getDropSql(), ZendDbSchema_Db_Schema_Table_Index\_getDropSql(), ZendDbSchema_Db_Schema_Table_ForeignKey\_getDropSql(), ZendDbSchema_Db_Schema_Table_Column\_getDropSql(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\addForeignKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\addForeignKey(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\addPrimaryKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\addPrimaryKey(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterColumn(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\createIndex(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\createIndex(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\dropColumn(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\dropColumn(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\dropForeignKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\dropForeignKey(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\dropIndex(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\dropIndex(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\dropPrimaryKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\dropPrimaryKey(), and toSql().
ZendDbSchema_Db_Schema_Table_AbstractDefinition::isDeleted ()
Check if definition marked to delete
Returns:
boolen
Definition at line 170 of file AbstractDefinition.php.
Referenced by isDirty(), and toSql().
ZendDbSchema_Db_Schema_Table_AbstractDefinition::isDirty ($param = null)
See also:
ZendDbSchema_Db_Schema_AbstractSchema::isDirty()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 115 of file AbstractDefinition.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Pgsql_Table\alterColumn(), and ZendDbSchema_Db_Schema_Generator_Mysql_Table\alterColumn().
ZendDbSchema_Db_Schema_Table_AbstractDefinition::markDeleted ($toDelete = true)
Mark definition to delete
Parameters:
boolen $toDelete
Returns:
ZendDbSchema_Db_Schema_Table_AbstractDefinition
Definition at line 156 of file AbstractDefinition.php.
ZendDbSchema_Db_Schema_Table_AbstractDefinition::toSql ($alter = false)
Get sql query
Returns:
string
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 128 of file AbstractDefinition.php.
The documentation for this class was generated from the following file:
Db/Schema/Table/AbstractDefinition.php