ZendDbSchema: ZendDbSchema_Db_Schema_Validator_AbstractValidator Class Reference
ZendDbSchema_Db_Schema_Validator_AbstractValidator Class Reference
Public Member Functions
validateDatabase (ZendDbSchema_Db_Schema_Database $schema, $option, $value)
validateTable (ZendDbSchema_Db_Schema_Table $schema, $option, $value)
validateColumn (ZendDbSchema_Db_Schema_Table_Column $schema, $option, $value)
validateIndex (ZendDbSchema_Db_Schema_Table_Index $schema, $option, $value)
validatePrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema, $option, $value)
validateForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema, $option, $value)
validate (ZendDbSchema_Db_Schema_AbstractSchema $schema, $option=null, $value=null)
Detailed Description
Definition at line 29 of file AbstractValidator.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Validator_AbstractValidator::validate (ZendDbSchema_Db_Schema_AbstractSchema $ schema, $ option = null, $ value = null)
Check if option can be given value
Parameters:
ZendDbSchema_Db_Schema_AbstractSchema $schema
string $option
mixed $value
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 99 of file AbstractValidator.php.
ZendDbSchema_Db_Schema_Validator_AbstractValidator::validateColumn (ZendDbSchema_Db_Schema_Table_Column $ schema, $ option, $ value) [abstract]
Check if option can be given value
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
string $option
mixed $value
Exceptions:
ZendDbSchema_Db_Schema_Exception
Reimplemented in ZendDbSchema_Db_Schema_Validator_Mysql.
Referenced by validate().
ZendDbSchema_Db_Schema_Validator_AbstractValidator::validateDatabase (ZendDbSchema_Db_Schema_Database $ schema, $ option, $ value) [abstract]
Check if option can be given value
Parameters:
ZendDbSchema_Db_Schema_Database $schema
string $option
mixed $value
Exceptions:
ZendDbSchema_Db_Schema_Exception
Reimplemented in ZendDbSchema_Db_Schema_Validator_Mysql.
Referenced by validate().
ZendDbSchema_Db_Schema_Validator_AbstractValidator::validateForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $ schema, $ option, $ value) [abstract]
Check if option can be given value
Parameters:
ZendDbSchema_Db_Schema_Table_ForeignKey $schema
string $option
mixed $value
Exceptions:
ZendDbSchema_Db_Schema_Exception
Reimplemented in ZendDbSchema_Db_Schema_Validator_Mysql.
Referenced by validate().
ZendDbSchema_Db_Schema_Validator_AbstractValidator::validateIndex (ZendDbSchema_Db_Schema_Table_Index $ schema, $ option, $ value) [abstract]
Check if option can be given value
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
string $option
mixed $value
Exceptions:
ZendDbSchema_Db_Schema_Exception
Reimplemented in ZendDbSchema_Db_Schema_Validator_Mysql.
Referenced by validate().
ZendDbSchema_Db_Schema_Validator_AbstractValidator::validatePrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $ schema, $ option, $ value) [abstract]
Check if option can be given value
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
string $option
mixed $value
Exceptions:
ZendDbSchema_Db_Schema_Exception
Reimplemented in ZendDbSchema_Db_Schema_Validator_Mysql.
Referenced by validate().
ZendDbSchema_Db_Schema_Validator_AbstractValidator::validateTable (ZendDbSchema_Db_Schema_Table $ schema, $ option, $ value) [abstract]
Check if option can be given value
Parameters:
ZendDbSchema_Db_Schema_Table $schema
string $option
mixed $value
Exceptions:
ZendDbSchema_Db_Schema_Exception
Reimplemented in ZendDbSchema_Db_Schema_Validator_Mysql.
Referenced by validate().
The documentation for this class was generated from the following file:
Db/Schema/Validator/AbstractValidator.php