ZendDbSchema: ZendDbSchema_Db_Schema_Generator_Mysql Class Reference
ZendDbSchema_Db_Schema_Generator_Mysql Class Reference
Public Member Functions
createDatabase (ZendDbSchema_Db_Schema_Database $schema)
alterDatabase (ZendDbSchema_Db_Schema_Database $schema)
dropDatabase (ZendDbSchema_Db_Schema_Database $schema)
createTable (ZendDbSchema_Db_Schema_Table $schema)
alterTable (ZendDbSchema_Db_Schema_Table $schema)
dropTable (ZendDbSchema_Db_Schema_Table $schema)
createColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
alterColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
dropColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
createIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
alterIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
dropIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
addPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
alterPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
dropPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
addForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
alterForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
dropForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
createDatabase (ZendDbSchema_Db_Schema_Database $schema)
alterDatabase (ZendDbSchema_Db_Schema_Database $schema)
dropDatabase (ZendDbSchema_Db_Schema_Database $schema)
createTable (ZendDbSchema_Db_Schema_Table $schema)
alterTable (ZendDbSchema_Db_Schema_Table $schema)
dropTable (ZendDbSchema_Db_Schema_Table $schema)
createColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
alterColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
dropColumn (ZendDbSchema_Db_Schema_Table_Column $schema)
createIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
alterIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
dropIndex (ZendDbSchema_Db_Schema_Table_Index $schema)
addPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
dropPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $schema)
addForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
alterForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
dropForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $schema)
Protected Member Functions
_columnSql (ZendDbSchema_Db_Schema_Table_Column $schema)
_columnSql (ZendDbSchema_Db_Schema_Table_Column $schema)
Detailed Description
Definition at line 29 of file Mysql.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Generator_Mysql::_columnSql (ZendDbSchema_Db_Schema_Table_Column $ schema) [protected]
Generate
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Definition at line 196 of file Mysql.php.
Referenced by alterColumn(), and createColumn().
ZendDbSchema_Db_Schema_Generator_Mysql::_columnSql (ZendDbSchema_Db_Schema_Table_Column $ schema) [protected]
Generate
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Definition at line 220 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::addForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $ schema)
Generate CREATE FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_ForeignKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 387 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::addForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $ schema)
Generate CREATE FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_ForeignKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 392 of file Mysql.php.
Referenced by alterForeignKey().
ZendDbSchema_Db_Schema_Generator_Mysql::addPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $ schema)
Generate ADD PRIMARY KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 347 of file Mysql.php.
Referenced by alterPrimaryKey().
ZendDbSchema_Db_Schema_Generator_Mysql::addPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $ schema)
Generate ADD PRIMARY KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 357 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterColumn (ZendDbSchema_Db_Schema_Table_Column $ schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 250 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterColumn (ZendDbSchema_Db_Schema_Table_Column $ schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 260 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterDatabase (ZendDbSchema_Db_Schema_Database $ schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Database $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 64 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterDatabase (ZendDbSchema_Db_Schema_Database $ schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Database $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 75 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $ schema)
Generate ALTER FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_ForeignKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 421 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $ schema)
Generate ALTER FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_ForeignKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 426 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterIndex (ZendDbSchema_Db_Schema_Table_Index $ schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 321 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterIndex (ZendDbSchema_Db_Schema_Table_Index $ schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 331 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $ schema)
Generate ALTER PRIMARY KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Definition at line 363 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterTable (ZendDbSchema_Db_Schema_Table $ schema)
Generate ALTER TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 142 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::alterTable (ZendDbSchema_Db_Schema_Table $ schema)
Generate ALTER TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 169 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::createColumn (ZendDbSchema_Db_Schema_Table_Column $ schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 238 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::createColumn (ZendDbSchema_Db_Schema_Table_Column $ schema)
Generate ALTER DATABASE
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 248 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::createDatabase (ZendDbSchema_Db_Schema_Database $ schema)
Generate CREATE DATABASE
Parameters:
ZendDbSchema_Db_Schema_Database $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 38 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::createDatabase (ZendDbSchema_Db_Schema_Database $ schema)
Generate CREATE DATABASE
Parameters:
ZendDbSchema_Db_Schema_Database $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 38 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::createIndex (ZendDbSchema_Db_Schema_Table_Index $ schema)
Generate CREATE INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 295 of file Mysql.php.
Referenced by alterIndex().
ZendDbSchema_Db_Schema_Generator_Mysql::createIndex (ZendDbSchema_Db_Schema_Table_Index $ schema)
Generate CREATE INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 305 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::createTable (ZendDbSchema_Db_Schema_Table $ schema)
Generate CREATE TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 106 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::createTable (ZendDbSchema_Db_Schema_Table $ schema)
Generate CREATE TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 124 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropColumn (ZendDbSchema_Db_Schema_Table_Column $ schema)
Generate CREATE INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 281 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropColumn (ZendDbSchema_Db_Schema_Table_Column $ schema)
Generate CREATE INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Column $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 291 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropDatabase (ZendDbSchema_Db_Schema_Database $ schema)
Generate DROP DATABASE
Parameters:
ZendDbSchema_Db_Schema_Database $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 92 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropDatabase (ZendDbSchema_Db_Schema_Database $ schema)
Generate DROP DATABASE
Parameters:
ZendDbSchema_Db_Schema_Database $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 110 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $ schema)
Generate DROP FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 437 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropForeignKey (ZendDbSchema_Db_Schema_Table_ForeignKey $ schema)
Generate DROP FOREIGN KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 442 of file Mysql.php.
Referenced by alterForeignKey().
ZendDbSchema_Db_Schema_Generator_Mysql::dropIndex (ZendDbSchema_Db_Schema_Table_Index $ schema)
Generate DROP INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 332 of file Mysql.php.
Referenced by createIndex().
ZendDbSchema_Db_Schema_Generator_Mysql::dropIndex (ZendDbSchema_Db_Schema_Table_Index $ schema)
Generate DROP INDEX
Parameters:
ZendDbSchema_Db_Schema_Table_Index $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 342 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $ schema)
Generate DROP PRIMARY KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 373 of file Pgsql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropPrimaryKey (ZendDbSchema_Db_Schema_Table_PrimaryKey $ schema)
Generate DROP PRIMARY KEY
Parameters:
ZendDbSchema_Db_Schema_Table_PrimaryKey $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 378 of file Mysql.php.
Referenced by alterPrimaryKey().
ZendDbSchema_Db_Schema_Generator_Mysql::dropTable (ZendDbSchema_Db_Schema_Table $ schema)
Generate DROP TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 182 of file Mysql.php.
ZendDbSchema_Db_Schema_Generator_Mysql::dropTable (ZendDbSchema_Db_Schema_Table $ schema)
Generate DROP TABLE
Parameters:
ZendDbSchema_Db_Schema_Table $schema
Returns:
string
Implements ZendDbSchema_Db_Schema_Generator_Interface.
Definition at line 206 of file Pgsql.php.
The documentation for this class was generated from the following files:
Db/Schema/Generator/Mysql.php
Db/Schema/Generator/Pgsql.php