ZendDbSchema: ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager Class Reference
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager Class Reference
Public Member Functions
__construct (ZendDbSchema_Db_Schema_Table $table)
refresh ()
setFromArray (array $config)
add (ZendDbSchema_Db_Schema_Table_AbstractDefinition $item)
isDirty ()
toArray ()
getIterator ()
has ($name)
get ($name)
count ()
Protected Member Functions
_getItemClass ()
_getSchemaKey ()
Protected Attributes
$_data = array()
$_table
Detailed Description
Definition at line 29 of file AbstractManager.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::__construct (ZendDbSchema_Db_Schema_Table $table)
Constructor
Parameters:
ZendDbSchema_Db_Schema_Table $table
Exceptions:
ZendDbSchema_Db_Schema_Exception
Definition at line 62 of file AbstractManager.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::_getItemClass () abstract protected
Get classname
Returns:
string
Reimplemented in ZendDbSchema_Db_Schema_Table_DefinitionManager_Column, ZendDbSchema_Db_Schema_Table_DefinitionManager_ForeignKey, and ZendDbSchema_Db_Schema_Table_DefinitionManager_Index.
Referenced by add(), refresh(), and setFromArray().
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::_getSchemaKey () abstract protected
Get classname
Returns:
string
Reimplemented in ZendDbSchema_Db_Schema_Table_DefinitionManager_Column, ZendDbSchema_Db_Schema_Table_DefinitionManager_ForeignKey, and ZendDbSchema_Db_Schema_Table_DefinitionManager_Index.
Referenced by refresh().
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::add (ZendDbSchema_Db_Schema_Table_AbstractDefinition $item)
Add index
Parameters:
ZendDbSchema_Db_Schema_Table_Index $index
Returns:
self
Definition at line 119 of file AbstractManager.php.
Referenced by setFromArray().
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::count ()
Countable interface
Returns:
integer
Definition at line 211 of file AbstractManager.php.
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::get ($name)
Get item
Parameters:
string $name
Returns:
boolen
Definition at line 196 of file AbstractManager.php.
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::getIterator ()
See also:
IteratorAggregate::getIterator()
Returns:
ArrayIterator
Definition at line 174 of file AbstractManager.php.
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::has ($name)
Has item
Parameters:
string $name
Returns:
false|array index
Definition at line 185 of file AbstractManager.php.
Referenced by add(), and setFromArray().
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::isDirty ()
Is items dirty
Returns:
boolean
Definition at line 145 of file AbstractManager.php.
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::refresh ()
Refresh
Returns:
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager
Definition at line 74 of file AbstractManager.php.
Referenced by __construct().
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::setFromArray (array $config)
Set from array
Parameters:
array $config
Returns:
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager
Definition at line 95 of file AbstractManager.php.
Referenced by refresh().
ZendDbSchema_Db_Schema_Table_DefinitionManager_AbstractManager::toArray ()
To array
Returns:
array
Definition at line 160 of file AbstractManager.php.
The documentation for this class was generated from the following file:
Db/Schema/Table/DefinitionManager/AbstractManager.php