ZendDbSchema: ZendDbSchema_Db_Migration_Skeleton Class Reference
ZendDbSchema_Db_Migration_Skeleton Class Reference
Public Member Functions
__construct (Zend_CodeGenerator_Php_Class $class=null)
setMethodUp ($body= '//rollup')
setMethodDown ($body= '//rolldown')
addSchema (array $tablesList=array(), array $databasesList=array())
setVersion ($version)
getVersion ()
getFile ()
write ()
getClass ()
getAdapter ()
setAdapter (ZendDbSchema_Db_Adapter_SchemaCompatible $adapter)
Static Public Member Functions
static getClassName ($version)
static generateVersion ()
static getFilename ($version)
Protected Attributes
$_adapter
$_version
$_class
Detailed Description
Definition at line 29 of file Skeleton.php.
Constructor & Destructor Documentation
ZendDbSchema_Db_Migration_Skeleton::__construct (Zend_CodeGenerator_Php_Class $ class = null)
Constructor
Parameters:
Zend_CodeGenerator_Php_Class $class
Definition at line 51 of file Skeleton.php.
Member Function Documentation
ZendDbSchema_Db_Migration_Skeleton::addSchema (array $ tablesList = array(), array $ databasesList = array())
Add schema
Parameters:
array $tablesList
array $databasesList
Definition at line 93 of file Skeleton.php.
static ZendDbSchema_Db_Migration_Skeleton::generateVersion () [static]
Generate version
Returns:
string
Definition at line 243 of file Skeleton.php.
Referenced by ZendDbSchema_Tool_Project_Provider_Migration\createResource().
ZendDbSchema_Db_Migration_Skeleton::getAdapter ()
Get adapter
Exceptions:
ZendDbSchema_Db_Migration_Exception
Returns:
Zend_Db_Adapter_Abstract
Definition at line 206 of file Skeleton.php.
Referenced by addSchema().
ZendDbSchema_Db_Migration_Skeleton::getClass ()
Get class
Returns:
Zend_CodeGenerator_Php_Class
Definition at line 195 of file Skeleton.php.
Referenced by getFile(), and setVersion().
static ZendDbSchema_Db_Migration_Skeleton::getClassName ($ version) [static]
Get class name
Parameters:
string $version
Returns:
string
Definition at line 233 of file Skeleton.php.
Referenced by ZendDbSchema_Db_Migration_Change\fromFile().
ZendDbSchema_Db_Migration_Skeleton::getFile ()
Get file
Returns:
Zend_CodeGenerator_Php_File
Definition at line 169 of file Skeleton.php.
Referenced by write().
static ZendDbSchema_Db_Migration_Skeleton::getFilename ($ version) [static]
Get filename
Parameters:
string $version
Definition at line 254 of file Skeleton.php.
Referenced by ZendDbSchema_Tool_Project_Provider_Migration\createResource().
ZendDbSchema_Db_Migration_Skeleton::getVersion ()
Get version
Returns:
string
Definition at line 156 of file Skeleton.php.
Referenced by getFile().
ZendDbSchema_Db_Migration_Skeleton::setAdapter (ZendDbSchema_Db_Adapter_SchemaCompatible $ adapter)
Set adapter
Parameters:
ZendDbSchema_Db_Adapter_SchemaCompatible $adapter
Returns:
self
Definition at line 221 of file Skeleton.php.
Referenced by getAdapter().
ZendDbSchema_Db_Migration_Skeleton::setMethodDown ($ body = '// rolldown')
Set Method up
Parameters:
string $body
Definition at line 79 of file Skeleton.php.
ZendDbSchema_Db_Migration_Skeleton::setMethodUp ($ body = '// rollup')
Set method down
Parameters:
string $body
Definition at line 66 of file Skeleton.php.
ZendDbSchema_Db_Migration_Skeleton::setVersion ($ version)
Set version
Parameters:
string $version
Returns:
ZendDbSchema_Db_Migration_Skeleton
Definition at line 142 of file Skeleton.php.
Referenced by getVersion().
ZendDbSchema_Db_Migration_Skeleton::write ()
Write file
Returns:
self
Definition at line 183 of file Skeleton.php.
The documentation for this class was generated from the following file:
Db/Migration/Skeleton.php