ZendDbSchema: ZendDbSchema_Db_Schema_Table_ForeignKey Class Reference
ZendDbSchema_Db_Schema_Table_ForeignKey Class Reference
Public Member Functions
setReferences ($table)
getReferences ()
setColumns (array $columns)
hasColumn ($columnName)
hasRefColumn ($refColumnName)
setColumn ($columnName, $refColumnName)
getColumns ()
removeColumn ($columnName)
setOnDelete ($onDelete)
getOnDelete ()
setOnUpdate ($onUpdate)
getOnUpdate ()
Public Member Functions inherited from ZendDbSchema_Db_Schema_Table_AbstractDefinition
__construct ($name, ZendDbSchema_Db_Schema_Table $table=null)
__clone ()
__set ($name, $value)
isDirty ($param=null)
toSql ($alter=false)
getTable ()
markDeleted ($toDelete=true)
isDeleted ()
Public Member Functions inherited from ZendDbSchema_Db_Schema_AbstractSchema
isExist ()
getCleanSchema ($param=null)
refresh ($param=null)
__construct ($name=null)
init ()
__toString ()
__get ($name)
__isset ($name)
__unset ($name)
getIterator ()
setFromArray (array $schema)
toArray ()
setName ($name)
getName ()
getOriginName ()
getDropSql ()
Public Attributes
const COLUMNS_KEY = 'columns'
const REFERENCE_KEY = 'references'
const ONDELETE_KEY = 'delete'
const ONUPDATE_KEY = 'update'
Protected Member Functions
_getSchemaKey ()
_getDropSql ()
_getAlterSql ()
_getCreateSql ()
Protected Member Functions inherited from ZendDbSchema_Db_Schema_Table_AbstractDefinition
_getCleanSchema ()
Additional Inherited Members
Protected Attributes inherited from ZendDbSchema_Db_Schema_Table_AbstractDefinition
$_table
$_toDelete
Protected Attributes inherited from ZendDbSchema_Db_Schema_AbstractSchema
$_params = array()
$_name
Detailed Description
Definition at line 29 of file ForeignKey.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Table_ForeignKey::_getAlterSql () protected
See also:
ZendDbSchema_Db_Schema_Table_AbstractDefinition::_getAlterSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 58 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::_getCreateSql () protected
See also:
ZendDbSchema_Db_Schema_Table_AbstractDefinition::_getCreateSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 66 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::_getDropSql () protected
See also:
ZendDbSchema_Db_Schema_AbstractSchema::_getDropSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 50 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::_getSchemaKey () protected
Get schema key
Returns:
string
Reimplemented from ZendDbSchema_Db_Schema_Table_AbstractDefinition.
Definition at line 42 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::getColumns ()
Get columns
Returns:
array
Definition at line 157 of file ForeignKey.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Pgsql_Table\addForeignKey(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\addForeignKey(), hasColumn(), hasRefColumn(), removeColumn(), and setColumn().
ZendDbSchema_Db_Schema_Table_ForeignKey::getOnDelete ()
Get ON DELETE option
Returns:
string
Definition at line 197 of file ForeignKey.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Pgsql_Table\addForeignKey(), and ZendDbSchema_Db_Schema_Generator_Mysql_Table\addForeignKey().
ZendDbSchema_Db_Schema_Table_ForeignKey::getOnUpdate ()
Get ON UPDATE option
Returns:
string
Definition at line 220 of file ForeignKey.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Pgsql_Table\addForeignKey(), and ZendDbSchema_Db_Schema_Generator_Mysql_Table\addForeignKey().
ZendDbSchema_Db_Schema_Table_ForeignKey::getReferences ()
Get reference table
Returns:
string
Definition at line 96 of file ForeignKey.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Pgsql_Table\addForeignKey(), and ZendDbSchema_Db_Schema_Generator_Mysql_Table\addForeignKey().
ZendDbSchema_Db_Schema_Table_ForeignKey::hasColumn ($columnName)
Has column
Parameters:
string $columnName
Returns:
boolen
Definition at line 119 of file ForeignKey.php.
Referenced by removeColumn().
ZendDbSchema_Db_Schema_Table_ForeignKey::hasRefColumn ($refColumnName)
Has column
Parameters:
string $columnName
Returns:
boolen
Definition at line 130 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::removeColumn ($columnName)
Remove column
Parameters:
string $columnName
Returns:
boolen
Definition at line 170 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::setColumn ($columnName, $refColumnName)
Set column
Parameters:
string $columnName
string $refColumnName
Returns:
boolen
Definition at line 143 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::setColumns (array $columns)
Set columns
Parameters:
array $columns
Returns:
self
Definition at line 107 of file ForeignKey.php.
Referenced by removeColumn(), and setColumn().
ZendDbSchema_Db_Schema_Table_ForeignKey::setOnDelete ($onDelete)
Set ON DELETE option
Parameters:
string $onDelete
Returns:
self
Definition at line 186 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::setOnUpdate ($onUpdate)
Set ON UPDATE option
Parameters:
string $onUpdate
Returns:
self
Definition at line 209 of file ForeignKey.php.
ZendDbSchema_Db_Schema_Table_ForeignKey::setReferences ($table)
Set reference table
Parameters:
string | ZendDbSchema_Db_Schema_Table $table
Returns:
self
Definition at line 77 of file ForeignKey.php.
The documentation for this class was generated from the following file:
Db/Schema/Table/ForeignKey.php