ZendDbSchema: ZendDbSchema_Db_Schema_Table_Index Class Reference
ZendDbSchema_Db_Schema_Table_Index Class Reference
Public Member Functions
setColumns (array $columns)
hasColumn ($columnName)
addColumn ($columnName)
getColumns ()
removeColumn ($columnName)
Public Member Functions inherited from ZendDbSchema_Db_Schema_Table_AbstractDefinition
__construct ($name, ZendDbSchema_Db_Schema_Table $table=null)
__clone ()
__set ($name, $value)
isDirty ($param=null)
toSql ($alter=false)
getTable ()
markDeleted ($toDelete=true)
isDeleted ()
Public Member Functions inherited from ZendDbSchema_Db_Schema_AbstractSchema
isExist ()
getCleanSchema ($param=null)
refresh ($param=null)
__construct ($name=null)
init ()
__toString ()
__get ($name)
__isset ($name)
__unset ($name)
getIterator ()
setFromArray (array $schema)
toArray ()
setName ($name)
getName ()
getOriginName ()
getDropSql ()
Public Attributes
const COLUMNS_KEY = 'columns'
const TYPE_KEY = 'type'
Protected Member Functions
_getSchemaKey ()
_getDropSql ()
_getAlterSql ()
_getCreateSql ()
Protected Member Functions inherited from ZendDbSchema_Db_Schema_Table_AbstractDefinition
_getCleanSchema ()
Additional Inherited Members
Protected Attributes inherited from ZendDbSchema_Db_Schema_Table_AbstractDefinition
$_table
$_toDelete
Protected Attributes inherited from ZendDbSchema_Db_Schema_AbstractSchema
$_params = array()
$_name
Detailed Description
Definition at line 29 of file Index.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Table_Index::_getAlterSql () protected
See also:
ZendDbSchema_Db_Schema_Table_AbstractDefinition::_getAlterSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 56 of file Index.php.
ZendDbSchema_Db_Schema_Table_Index::_getCreateSql () protected
See also:
ZendDbSchema_Db_Schema_Table_AbstractDefinition::_getCreateSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 64 of file Index.php.
ZendDbSchema_Db_Schema_Table_Index::_getDropSql () protected
See also:
ZendDbSchema_Db_Schema_AbstractSchema::_getDropSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 48 of file Index.php.
ZendDbSchema_Db_Schema_Table_Index::_getSchemaKey () protected
Get schema key
Returns:
string
Reimplemented from ZendDbSchema_Db_Schema_Table_AbstractDefinition.
Definition at line 40 of file Index.php.
ZendDbSchema_Db_Schema_Table_Index::addColumn ($columnName)
Add column
Parameters:
string $columnName
Returns:
boolen
Definition at line 98 of file Index.php.
ZendDbSchema_Db_Schema_Table_Index::getColumns ()
Get columns
Returns:
array
Definition at line 113 of file Index.php.
Referenced by addColumn(), ZendDbSchema_Db_Schema_Generator_Pgsql_Table\createIndex(), ZendDbSchema_Db_Schema_Generator_Mysql_Table\createIndex(), hasColumn(), and removeColumn().
ZendDbSchema_Db_Schema_Table_Index::hasColumn ($columnName)
Has column
Parameters:
string $columnName
Returns:
boolen
Definition at line 87 of file Index.php.
Referenced by addColumn(), and removeColumn().
ZendDbSchema_Db_Schema_Table_Index::removeColumn ($columnName)
Remove column
Parameters:
string $columnName
Returns:
boolen
Definition at line 125 of file Index.php.
ZendDbSchema_Db_Schema_Table_Index::setColumns (array $columns)
Set columns
Parameters:
array $columns
Returns:
self
Definition at line 75 of file Index.php.
Referenced by addColumn(), and removeColumn().
The documentation for this class was generated from the following file:
Db/Schema/Table/Index.php