ZendDbSchema: ZendDbSchema_Db_Schema_Database Class Reference
ZendDbSchema_Db_Schema_Database Class Reference
Public Member Functions
setValidator (Zend_Validate_Interface $validator)
setCharset ($charset)
getCharset ()
__set ($name, $value)
Public Attributes
const CHARSET_KEY = 'charset'
Protected Member Functions
_getAlterSql ()
_getCreateSql ()
_getDropSql ()
_doReload ()
Detailed Description
Definition at line 29 of file Database.php.
Member Function Documentation
ZendDbSchema_Db_Schema_Database::__set ($ name, $ value)
Set schema params
Parameters:
string $name
array $value
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 116 of file Database.php.
Referenced by setCharset().
ZendDbSchema_Db_Schema_Database::_doReload () [protected]
Reload database schema
Returns:
boolen
Reimplemented from ZendDbSchema_Db_Schema_AbstractEntity.
Definition at line 80 of file Database.php.
ZendDbSchema_Db_Schema_Database::_getAlterSql () [protected]
See also:
ZendDbSchema_Db_Schema_AbstractEntity::_getAlterSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 54 of file Database.php.
ZendDbSchema_Db_Schema_Database::_getCreateSql () [protected]
See also:
ZendDbSchema_Db_Schema_AbstractEntity::_getCreateSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 62 of file Database.php.
ZendDbSchema_Db_Schema_Database::_getDropSql () [protected]
See also:
ZendDbSchema_Db_Schema_AbstractSchema::_getDropSql()
Reimplemented from ZendDbSchema_Db_Schema_AbstractSchema.
Definition at line 70 of file Database.php.
ZendDbSchema_Db_Schema_Database::getCharset ()
Get charset
Returns:
string
Definition at line 105 of file Database.php.
Referenced by ZendDbSchema_Db_Schema_Generator_Mysql\alterDatabase(), and ZendDbSchema_Db_Schema_Generator_Mysql\createDatabase().
ZendDbSchema_Db_Schema_Database::setCharset ($ charset)
Set charset
Parameters:
string $name
Returns:
self
Definition at line 94 of file Database.php.
ZendDbSchema_Db_Schema_Database::setValidator (Zend_Validate_Interface $ validator)
Set schema validator
Parameters:
ZendDbSchema_Validate_Db_Schema_AbstractDatabase $validator
Returns:
self
Reimplemented from ZendDbSchema_Db_Schema_AbstractEntity.
Definition at line 40 of file Database.php.
The documentation for this class was generated from the following file:
Db/Schema/Database.php