ZendDbSchema: ZendDbSchema_Db_Migration_Change Class Reference
ZendDbSchema_Db_Migration_Change Class Reference
Public Member Functions
up ()
down ()
__toString ()
getName ()
getDescription ()
isDowngradable ()
getTablesConfig ()
getDatabasesConfig ()
getVersion ()
compareVersion ($version, $operator=null)
Static Public Member Functions
static fromFile ($file)
Protected Attributes
$_downgradable = true
$_databasesConfig = array()
$_tablesConfig = array()
$_description = ''
Detailed Description
Definition at line 29 of file Change.php.
Member Function Documentation
ZendDbSchema_Db_Migration_Change::__toString ()
Get version
Definition at line 65 of file Change.php.
ZendDbSchema_Db_Migration_Change::compareVersion ($version, $operator = null)
Compare version
Parameters:
string | ZendDbSchema_Db_Migration_Change $version
string $operator
Exceptions:
ZendDbSchema_Db_Migration_Exception
Returns:
1|-1|0|true|false
Definition at line 138 of file Change.php.
ZendDbSchema_Db_Migration_Change::down () abstract
Down
static ZendDbSchema_Db_Migration_Change::fromFile ($file) static
Get instance from file
Parameters:
string | SplFileObject $file
Returns:
ZendDbSchema_Db_Migration_Change
Exceptions:
ZendDbSchema_Db_Migration_Exception
Definition at line 156 of file Change.php.
Referenced by ZendDbSchema_Db_Migration_Manager\addChange(), and ZendDbSchema_Tool_Project_Provider_Migration\show().
ZendDbSchema_Db_Migration_Change::getDatabasesConfig ()
Get databases schema config
Returns:
array
Definition at line 115 of file Change.php.
ZendDbSchema_Db_Migration_Change::getDescription ()
Get migration desription
Returns:
string
Definition at line 85 of file Change.php.
ZendDbSchema_Db_Migration_Change::getName ()
Get name
Returns:
string
Definition at line 75 of file Change.php.
ZendDbSchema_Db_Migration_Change::getTablesConfig ()
Get tables schema config
Returns:
array
Definition at line 105 of file Change.php.
ZendDbSchema_Db_Migration_Change::getVersion ()
Get version
Returns:
string
Definition at line 125 of file Change.php.
Referenced by __toString(), and compareVersion().
ZendDbSchema_Db_Migration_Change::isDowngradable ()
Is migration downgradable
Returns:
boolean
Definition at line 95 of file Change.php.
ZendDbSchema_Db_Migration_Change::up () abstract
Up
The documentation for this class was generated from the following file:
Db/Migration/Change.php